project_id = "idcfieikxrcopimxfxup"

[functions.admin-api]
verify_jwt = false

[functions.tasks-admin]
verify_jwt = false

[functions.auth-emails]
verify_jwt = false

[functions.process-referral]
verify_jwt = true

[functions.database-cleanup]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.admin-settings]
verify_jwt = false

[functions.export-users]
verify_jwt = false
